### PR TITLE
Clarify examples in README

### PR DESCRIPTION
**Pull request by nertzy**

### CODE REVIEW

**Comment by nertzy** [comment]
I signed the CLA.

**Comment by pmdartus** [comment]
Thanks for your contribution @nertzy. 
I don't see your username list of users who signed the CLA. Do you mind signing the CLA again?

**Comment by nertzy** [comment]
I signed it again.

**Review by pmdartus — APPROVED** [review]

**Comment by pmdartus** [comment]
Thanks for your contribution @nertzy.

**Pull request merged**
